server:
  port: 0

spring:
  application:
    name: account
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update

