CREATE TABLE IF NOT EXISTS public.account_info (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255),
    full_name VARCHAR(255),
    age INT,
    is_active BOOLEAN,
    CONSTRAINT pk_account_info PRIMARY KEY (id)
);

INSERT INTO account_info (username, full_name, age, is_active) VALUES ('Hamelion', 'Michael Nikitin', 25, true);