server:
  port: 8070

eureka:
  instance:
    hostname: eureka-server
    preferIpAddress: true
  server:
    waitTimeInMsWhenSyncEmpty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"

