spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/news_feed_database
    username: postgres
    password: '{cipher}686b55a71a971471f44257116065ee718d20bd843ab7e94baf0dd00b6487833c'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

resilience4j:
  circuitbreaker:
    instance:
      newsFeedService:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException


management:
  health:
    circulitbreakers:
      enabled: true
    ratelimiters: true
  endpoints:
    health: always
    web:
      exposure:
        include: "*"